<?php

$file = "<?php\nnamespace html;\n\n";
$tags = array(
	'img', 
	'br', 
	'hr',
	'table',
	'thead',
	'tbody',
	'th',
	'tr',
	'td',
	'span',
	'p', 
	'h1', 
	'h2', 
	'h3', 
	'h4', 
	'h5', 
	'html', 
	'head',
	'title', 
	'body', 
	'meta', 
	'div', 
	'script', 
	'link', 
	'style',
	'ul', 
	'li', 
	'ol', 
	'a', 
	'form',
	'textarea', 
	'input', 
	'pre',
	'label', 
	'select', 
	'option',
	'button', 
	'fieldset', 
	'legend');
foreach($tags as $tag) {
	
	$file .= "function $tag() {\n\treturn new Node('$tag', func_get_args(), " . (in_array($tag, array('br', 'hr', 'img', 'meta', 'link', 'input')) ? 'true' : 'false') . ");\n}\n" . 
			 "function " . ($tag == 'a' ? '_as' : "{$tag}s") . "(){\n\treturn tags('{$tag}', func_get_args());\n}\n";
}

foreach(array_merge($tags, array(
	'extend' => 'mixin',
	'float',
	'mixin',
	'position',
	'left',
	'top',
	'right',
	'bottom',
	'font-size',
	'font-family',
	'font-weight',
	'text-align',
	'text-decoration',
	'outline',
	'display',
	'visibility', 
	'rel', 
	'width', 
	'height', 
	'cellpadding', 
	'cellspacing',
	'colspan', 
	'rowspan',
	'id', 
	'klass' => 'class', 
	'value', 
	'name', 
	'type', 
	'onchange',
	'onclick', 
	'ondblclick', 
	'onload', 
	'accesskey', 
	'tabindex', 
	'method',
	'action', 
	'href',
	'alt',
	'src', 
	'_for' => 'for', 
	'align', 
	'lang', 
	'dir', 
	'onmousedown', 
	'onmouseover', 
	'onmouseup', 
	'onmousemove', 
	'onmouseout', 
	'onkeypress', 
	'onkeydown', 
	'onkeyup', 
	'background', 
	'background-image',
	'background-repeat',
	'background-position',
	'color', 
	'border', 
	'border-left', 
	'border-right',
	'border-top',
	'border-bottom', 
	'margin', 
	'margin-left', 
	'margin-right', 
	'margin-top',
	'margin-bottom',
	'background-color', 
	'padding', 
	'padding-left', 
	'padding-right', 
	'content', 
	'-webkit-border-radius',
	'-moz-border-radius',
	'border-radius')) as $id => $name) {
	$const = str_replace('-', '_', is_numeric($id) ? $name : $id);
	//$name = chr(0) . $name;
	$file .= "const $const = '{$name}';\nconst " . strtoupper($const) . " = '{$name}';\n";
}

file_put_contents('tags.inc.php', $file);